version: "3.7"

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: /bin/bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"

    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - data-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /bin/bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - data-net

networks:
  data-net:
    external: true
